### ISSUE TITLE
The viewlink style is not working correctly

### ISSUE THREAD

**Issue by rayer4u** [django-cms/djangocms-admin-style#421]
The addlink,changelink style are override in djangocms-admin-style, but viewlink style is not. When django admin's has_change_permission function return false. the view button show not correct.
![1](https://user-images.githubusercontent.com/5928318/93425617-f1262280-f8ec-11ea-8aed-012b32f3ce4a.png)

**Comment by NarenderRajuB** [comment]
I am also experiencing the same issue for viewlink
