### ISSUE TITLE
Color input width broken by djangocms-admin.css

### ISSUE THREAD

**Issue by fallenflint** [django-cms/djangocms-admin-style#429]
## Description

Input type=color seems to be broken by djangocms-admin.css
![image](https://user-images.githubusercontent.com/6457827/101520997-44f95280-3996-11eb-9091-05de605cd067.png)
I've got color picker without color inside. A little investigation shown that issue connected to css rule `width: auto` for 
`button, input, select, textarea`. Disabling it fixes color input.

## Steps to reproduce

Simply use anything that renders to input type="color" on admin page.

## Expected behaviour

![image](https://user-images.githubusercontent.com/6457827/101521659-32334d80-3997-11eb-881e-ff98688fdd29.png)

Normal color input look.

## Actual behaviour

Broken color input without selected color visible

**Comment by fsbraun** [comment]
Solved in version 3.2.6
