### ISSUE TITLE
Disable dark theme

### ISSUE THREAD

**Issue by VoIlAlex** [django-cms/djangocms-admin-style#438]
I installed the package and in browsers with black theme enabled it displays table rows in dark colors. Is there a way to avoid this? 
![image](https://user-images.githubusercontent.com/37738312/117448363-5182d680-af47-11eb-84e5-9f939520bb12.png)

**Comment by DomicidalDesigns** [comment]
@VoIlAlex

I also saw this issue when django version 3.2 was installed but installing django 3.1 fixed it. Can you try installing django 3.1?
`python -m pip install -Iv django==3.1`

**Comment by VoIlAlex** [comment]
> @VoIlAlex
> 
> I also saw this issue when django version 3.2 was installed but installing django 3.1 fixed it. Can you try installing django 3.1?
> `python -m pip install -Iv django==3.1`

Thanks for your reply. I'll try.

**Comment by mike667** [comment]
Hi, how to fix this issue with django 3.2? Thanks

**Comment by greyhare** [comment]
IMHO the solution shouldn't be "disable dark theme" but instead "see how Django 3.2 uses dark theme and adjust our CSS to work with it."

**Comment by zotizzmoy** [comment]
pip install django-light
Add 'django_light', to INSTALLED_APPS before django.contrib.admin

This python package solve my problem.

**Comment by Aiky30** [comment]
> IMHO the solution shouldn't be "disable dark theme" but instead "see how Django 3.2 uses dark theme and adjust our CSS to work with it."

I agree, this should be fixed and not just disable it. There are some areas of complexity for this because this package uses scss and the django implementation is using native css variables. I'm not sure how we can get the two to play nicely together.

**Comment by fsbraun** [comment]
This will be solved by #443
