### ISSUE TITLE
Header box-shadow missing (CSS variables do not work in rgba)

### ISSUE THREAD

**Issue by petrklus** [django-cms/djangocms-admin-style#450]
The box-shadow seems to be broken in 3.1.0:

![image](https://user-images.githubusercontent.com/1115667/161705402-61ee7166-8a89-4ffc-9e0f-1464f9f32393.png)

When inspecting, seems that the colour is not being picked up:

![image](https://user-images.githubusercontent.com/1115667/161705489-247a2cf6-a6ab-4e00-8ee6-425e51fe9aab.png)

While in 3.0.0, it is resolved into a colour:

![image](https://user-images.githubusercontent.com/1115667/161705540-595815f8-9146-4cc9-9921-5056e78e963d.png)

I believe that this construct is not valid:

`rgba(var(--dca-black), 0.2`, which results from https://github.com/django-cms/djangocms-admin-style/blob/f026ee564f11600c033b1a73192c80fad3d51833/djangocms_admin_style/sass/settings/_cms.scss#L234

The solution is to either hard-code the colour value, or to define colours with alpha in them and then use them throughout.

I believe this would also affect `$hover-tooltip-bgcolor`, `$dropdown-shadow` and many others that now use CSS variables inside the rgba construct.

Tested on Mac OS 10.15.7, Chrome 100.0.4896.60

**Comment by petrklus** [comment]
@fsbraun I belive the above is related to the dark mode introduction, which changed the simple black/white colours (which worked in rgba construct) to CSS variables, which do not seem to resolve.

Would you be up for a new PR/amending yours to fix the above?

**Comment by fsbraun** [comment]
@petrklus I will look into it. Anyways, the shadows should have stayed black. Otherwise you'll get white shadows in dark mode which is strange. Will also check of other shadows might be affected. Thanks for pointing this out!

**Comment by petrklus** [comment]
Thank you @fsbraun ! Will keep an eye on the PR and test once released.
