### ISSUE TITLE
Documentation for building with gulp not working

### ISSUE THREAD

**Issue by MacLake** [django-cms/djangocms-admin-style#505]
The documentation for building the bundles with `gulp`  doesn’t work for me. When I build webpack bundles in my projects, I need to use `npx webpack`, not just `webpack`. With `npx gulp` at least I get an error message. Could you please update the instructions, so that it works?

**Comment by fsbraun** [comment]
I updated the readme.

**Comment by MacLake** [comment]
Thanks, `npx gulp icons sass bundle` works for me. If `gulp icons sass bundle` works in your setup, you must have `gulp` in your path (see `echo $PATH`). Can you check if you have `gulp-cli` installed globally like written in the gulp docs? `npm ls -g`. This makes `gulp`also available as a shell command. 

In that case it would be easier to just mention  `npx gulp icons sass bundle` which should always work.

**Comment by fsbraun** [comment]
PyCharm does add it to the path. I guess that's not universal ;-) Changed it.
