### ISSUE TITLE
Button layout/sizes with Django 4.2 and CMS 3.11

### ISSUE THREAD

**Issue by petrklus** [django-cms/djangocms-admin-style#506]
Upgraded a project to Django 4.2 and noticed odd action button layouts with djangocms-admin-style==3.2.7 and django-cms==3.11.4:

![image](https://github.com/django-cms/djangocms-admin-style/assets/1115667/6514efe4-f193-47f3-8d17-f0d831fe9509)

Also, the layout of the admin navbar is a bit odd:

![image](https://github.com/django-cms/djangocms-admin-style/assets/1115667/6050c617-317b-444b-84a8-5f45fd831b51)

For custom models, the actions row looks better but the buttons are still not aligned size-wise (the delete button is shorter than the others):

![image](https://github.com/django-cms/djangocms-admin-style/assets/1115667/8a27f853-2fa8-4b69-b2f1-975b29a7901a)

@fsbraun is the above expected with Django 4.2?

**Comment by fsbraun** [comment]
@petrklus Thanks for pointing out these inconsistencies!

Can you check if `pip install git+https://github.com/fsbraun/djangocms-admin-style@fix/django-4-2-submit-row` will solve your problem? Please let me know if there are other inconsistencies you notice!

**Comment by petrklus** [comment]
thank you for the quick response @fsbraun , will review your fix and also have a general poke around to see if anything else needs amending

**Comment by petrklus** [comment]
that fixed the issue @fsbraun - will now continue and review if I can spot any further issues, thank you for the fix!

**Comment by fsbraun** [comment]
@petrklus Any new observations? If not, I will go to release this.
